name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1
        with:
          host: 3.83.111.225
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: whoami